In [1]:
import torch

In [20]:
x= [1.0,20]
y =torch.arange(12)

In [21]:
print(x)
print(y)

[1.0, 20]
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [22]:
y.shape

torch.Size([12])

In [24]:
y.numel()


12

In [25]:
y.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
y.shape

torch.Size([12])

In [28]:
y.numel()

12

In [31]:
z = torch.zeros((2,3,4)) # 3x4 两张

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

In [43]:
x1 = torch.arange(12)
x1 = x1.reshape(3,4)

x2 = torch.zeros((3,4))

x3 = torch.ones((3,4))

x4 = torch.tensor( [[1,2,3,4],[2,3,4,5],[7,2,4,5]   ]  )

# test = torch.arange(10)
# test = test.reshape(5,2)


In [47]:
x2 , x3 ,x2+x3 ,x3+x3-x2-x1

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 2.,  1.,  0., -1.],
         [-2., -3., -4., -5.],
         [-6., -7., -8., -9.]]))

In [49]:
x1*x3

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])