In [55]:
import torch
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

In [56]:
x = torch.tensor([3.0])
x , x.shape

(tensor([3.]), torch.Size([1]))

In [57]:
y = torch.arange(4)
y ,  y.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [58]:
y[0] , y[1] , y[2] , y[3] 

(tensor(0), tensor(1), tensor(2), tensor(3))

In [59]:
A = torch.ones(20).reshape(4,5)
B = torch.zeros(20).reshape(4,5)  
C = torch.arange(20).reshape(4,5) 
A , B , C

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]))

In [60]:
a = torch.tensor([3.0])
b = torch.tensor([1.0])
c = a + b
d = a - b
e = a * b
f = a / b
a , b , c , d , e , f 

(tensor([3.]),
 tensor([1.]),
 tensor([4.]),
 tensor([2.]),
 tensor([3.]),
 tensor([3.]))

In [62]:
x = torch.arange(5)
y = torch.arange(5)
z = torch.dot(x,y)
x , y , z 

(tensor([0, 1, 2, 3, 4]), tensor([0, 1, 2, 3, 4]), tensor(30))

In [67]:
x , x.T ,  y , y.T , z , z.T

(tensor([0, 1, 2, 3, 4]),
 tensor([0, 1, 2, 3, 4]),
 tensor([0, 1, 2, 3, 4]),
 tensor([0, 1, 2, 3, 4]),
 tensor(30),
 tensor(30))

In [69]:
C , C.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

In [83]:
A = torch.arange(12).reshape(3,4)
B = torch.zeros(12).reshape(3,4)
C = torch.tensor([[1,2,3],[9,8,7],[2,5,3],[2,5,6]])
x = torch.arange(4)
y = torch.ones(4)
z = torch.zeros(4)

e1 = torch.mv(A,x)
e2 = torch.mm(A,C)

A , B , C ,x , y , z , e1 ,e2



(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1, 2, 3],
         [9, 8, 7],
         [2, 5, 3],
         [2, 5, 6]]),
 tensor([0, 1, 2, 3]),
 tensor([1., 1., 1., 1.]),
 tensor([0., 0., 0., 0.]),
 tensor([14, 38, 62]),
 tensor([[ 19,  33,  31],
         [ 75, 113, 107],
         [131, 193, 183]]))

In [92]:
A = torch.arange(24).reshape(2,3,4)
a0 =torch.sum(A,axis = 0)
a1 = torch.sum(A,axis = 1)
a2 = torch.sum(A,axis = 2)
A , a0 , a1 , a2

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))